// Package policy holds checks about the shape of this repository rather than
// about the behaviour of any one part of it.
package policy_test

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

// exempt are the directories this policy does not apply to.
var exempt = map[string]string{
	"ormopt": "generated by protoc-gen-go; its panics are the protobuf runtime's",
	"tools":  "developer commands, where crashing is a fine way to fail",
}

// TestNoPanicInGenerationPaths refuses panic() anywhere calque reasons about a
// schema, in either of the two ways it can be spelled.
//
// The predecessor had two, both spelled
// `default: panic("unimplemented: key type not Field")`, guarding a type switch
// over the same three-variant union. Both were wrong the same way: a unique
// edge used as a lookup key reached them. One was fixed in June. The other, at
// apps/db/app/app.go:330, still crashes the generator today.
//
// The point is not that panics are ugly. It is that a switch with a panicking
// default compiles when a variant is added, so the compiler stops helping
// exactly when the code stops being right. VisitElem and ElemVisitor exist so
// that the same situation is a build failure; this test is what stops someone
// reaching for the panic anyway.
//
// The second spelling is a call to something named Must or PanicIf. It is
// checked separately because it is invisible to the first: `panic(...)` is an
// *ast.Ident and `z.Use[T].Must(ctx)` is an *ast.SelectorExpr, so a commitment
// this test appears to enforce could be given up without the test noticing.
// The distinction that matters is not the spelling but when it runs -- see
// initCalls.
func TestNoPanicInGenerationPaths(t *testing.T) {
	root, err := filepath.Abs("../..")
	require.NoError(t, err)

	fset := token.NewFileSet()
	var offences []string
	var musts []string

	err = filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, relErr := filepath.Rel(root, path)
		if relErr != nil {
			return relErr
		}

		if d.IsDir() {
			name := d.Name()
			if name == ".git" || name == "node_modules" || name == "testdata" {
				return fs.SkipDir
			}
			if why, ok := exempt[rel]; ok {
				t.Logf("skipping %s: %s", rel, why)
				return fs.SkipDir
			}
			return nil
		}

		if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}

		src, readErr := os.ReadFile(path)
		if readErr != nil {
			return readErr
		}
		f, parseErr := parser.ParseFile(fset, path, src, 0)
		if parseErr != nil {
			return parseErr
		}

		atInit := initCalls(f)
		ast.Inspect(f, func(n ast.Node) bool {
			call, ok := n.(*ast.CallExpr)
			if !ok {
				return true
			}
			switch fun := call.Fun.(type) {
			case *ast.Ident:
				if fun.Name == "panic" {
					offences = append(offences, at(rel, fset, call))
				}
			case *ast.SelectorExpr:
				if mustLike(fun.Sel.Name) && !atInit[call] {
					musts = append(musts, at(rel, fset, call)+": "+selector(fun))
				}
			}
			return true
		})
		return nil
	})
	require.NoError(t, err)

	require.Empty(t, offences,
		"panic() in a path that reasons about a schema.\n"+
			"A switch with a panicking default keeps compiling when a variant is added,\n"+
			"which is when it stops being right. Use schema.VisitElem with an\n"+
			"ElemVisitor, or return a diagnostic, so the compiler or the user is told.")

	require.Empty(t, musts,
		"a Must or PanicIf call in a path that reasons about a schema.\n"+
			"These panic by contract and the spelling hides it, which is worse than a\n"+
			"bare panic rather than better. Read the value with the form that reports\n"+
			"absence -- From rather than Must -- or return an error.\n"+
			"A package-level var or const initialiser is exempt: it runs before there\n"+
			"is a request to fail.")
}

// mustLike reports whether a name promises to panic rather than to report.
//
// It matches on the name and not on the function it resolves to, because this
// test has to hold for a package the repository has not imported yet -- which
// is the whole reason it exists. A function called Must that does not panic is
// a worse problem than a false positive here.
func mustLike(name string) bool {
	return name == "PanicIf" || strings.HasPrefix(name, "Must")
}

// initCalls is every call in a package-level var or const initialiser.
//
// Those are exempt, and the reason is about when they run rather than about
// what they do. `var nameRE = regexp.MustCompile(...)` runs once at process
// start, before a request has been read: it cannot fail on a schema, and if
// the pattern is wrong the binary never starts rather than dying halfway
// through somebody's build.
//
// The walk stops at a func literal, because one inside an initialiser is not
// initialisation -- it runs when it is called, which is exactly when a request
// is in flight.
func initCalls(f *ast.File) map[ast.Node]bool {
	out := map[ast.Node]bool{}
	for _, decl := range f.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || (gd.Tok != token.VAR && gd.Tok != token.CONST) {
			continue
		}
		for _, spec := range gd.Specs {
			vs, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}
			for _, v := range vs.Values {
				ast.Inspect(v, func(n ast.Node) bool {
					if _, isLit := n.(*ast.FuncLit); isLit {
						return false
					}
					if call, isCall := n.(*ast.CallExpr); isCall {
						out[call] = true
					}
					return true
				})
			}
		}
	}
	return out
}

// at is a position said the way an editor can follow it.
func at(rel string, fset *token.FileSet, n ast.Node) string {
	p := fset.Position(n.Pos())
	return fmt.Sprintf("%s:%d:%d", rel, p.Line, p.Column)
}

// selector renders x.Sel when x is a plain identifier, which is enough to say
// which call a position points at.
func selector(e *ast.SelectorExpr) string {
	if x, ok := e.X.(*ast.Ident); ok {
		return x.Name + "." + e.Sel.Name
	}
	return e.Sel.Name
}

// TestGeneratedCodeIsMarked checks that every committed .pb.go says so, since
// the point of committing generated code is that a reader can tell.
func TestGeneratedCodeIsMarked(t *testing.T) {
	root, err := filepath.Abs("../..")
	require.NoError(t, err)

	err = filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if d.Name() == ".git" || d.Name() == "node_modules" {
				return fs.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".pb.go") {
			return nil
		}

		src, readErr := os.ReadFile(path)
		if readErr != nil {
			return readErr
		}
		rel, _ := filepath.Rel(root, path)
		// The convention every Go tool recognises, from the generated-code spec.
		require.Contains(t, string(src), "Code generated by",
			"%s does not say it is generated", rel)
		return nil
	})
	require.NoError(t, err)
}

// cliOnly are the modules that may be imported by the command tree and by
// nothing else.
//
// calque is a build-time plugin: what it imports lands in the go.mod of every
// repository that generates with it. A CLI framework is worth that for main
// and for cmd -- xlitest is what finally gave the plugin boundary a test -- and
// is not worth it for gen, schema, config, ormcompat or a target, which are the
// surface docs/extending.md documents and which a fork should be able to use
// without taking a command tree along.
//
// Both are pre-1.0 pseudo-versions with no frozen API. Keeping them in one
// package is what makes backing them out a change to one package.
var cliOnly = []string{
	"github.com/lesomnus/xli",
	"github.com/lesomnus/z",
}

// cliDirs are where cliOnly may be imported: the command tree, and main.
var cliDirs = map[string]bool{".": true, "cmd": true, "cmd/version": true}

// TestCliStaysInCmd is the rule above, checked.
//
// It reads imports rather than `go list -deps`, so it holds for test files too:
// a test that reaches for xlitest outside cmd is the first step towards the
// production code doing the same.
func TestCliStaysInCmd(t *testing.T) {
	root, err := filepath.Abs("../..")
	require.NoError(t, err)

	fset := token.NewFileSet()
	var offences []string

	err = filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if name := d.Name(); name == ".git" || name == "node_modules" || name == "testdata" {
				return fs.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") {
			return nil
		}

		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		if cliDirs[filepath.Dir(rel)] {
			return nil
		}

		f, err := parser.ParseFile(fset, path, nil, parser.ImportsOnly)
		if err != nil {
			return err
		}
		for _, spec := range f.Imports {
			p := strings.Trim(spec.Path.Value, `"`)
			for _, m := range cliOnly {
				if p == m || strings.HasPrefix(p, m+"/") {
					offences = append(offences, at(rel, fset, spec)+": "+p)
				}
			}
		}
		return nil
	})
	require.NoError(t, err)

	require.Empty(t, offences,
		"the CLI reached outside cmd.\n"+
			"calque is a build-time plugin, so what it imports goes into everybody's\n"+
			"go.mod. gen, schema, config, ormcompat and the targets are the documented\n"+
			"extension surface and stay on the standard library and protobuf.")
}
