// Package policy holds checks about the shape of this repository rather than
// about the behaviour of any one part of it.
package policy_test

import (
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

// exempt are the directories this policy does not apply to.
var exempt = map[string]string{
	"ormopt": "generated by protoc-gen-go; its panics are the protobuf runtime's",
	"tools":  "developer commands, where crashing is a fine way to fail",
}

// TestNoPanicInGenerationPaths refuses panic() anywhere calque reasons about a
// schema.
//
// The predecessor had two, both spelled
// `default: panic("unimplemented: key type not Field")`, guarding a type switch
// over the same three-variant union. Both were wrong the same way: a unique
// edge used as a lookup key reached them. One was fixed in June. The other, at
// apps/db/app/app.go:330, still crashes the generator today.
//
// The point is not that panics are ugly. It is that a switch with a panicking
// default compiles when a variant is added, so the compiler stops helping
// exactly when the code stops being right. VisitElem and ElemVisitor exist so
// that the same situation is a build failure; this test is what stops someone
// reaching for the panic anyway.
func TestNoPanicInGenerationPaths(t *testing.T) {
	root, err := filepath.Abs("../..")
	require.NoError(t, err)

	fset := token.NewFileSet()
	var offences []string

	err = filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, relErr := filepath.Rel(root, path)
		if relErr != nil {
			return relErr
		}

		if d.IsDir() {
			name := d.Name()
			if name == ".git" || name == "node_modules" || name == "testdata" {
				return fs.SkipDir
			}
			if why, ok := exempt[rel]; ok {
				t.Logf("skipping %s: %s", rel, why)
				return fs.SkipDir
			}
			return nil
		}

		if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}

		src, readErr := os.ReadFile(path)
		if readErr != nil {
			return readErr
		}
		f, parseErr := parser.ParseFile(fset, path, src, 0)
		if parseErr != nil {
			return parseErr
		}

		ast.Inspect(f, func(n ast.Node) bool {
			call, ok := n.(*ast.CallExpr)
			if !ok {
				return true
			}
			ident, ok := call.Fun.(*ast.Ident)
			if !ok || ident.Name != "panic" {
				return true
			}
			offences = append(offences,
				rel+":"+fset.Position(call.Pos()).String()[len(path)+1:])
			return true
		})
		return nil
	})
	require.NoError(t, err)

	require.Empty(t, offences,
		"panic() in a path that reasons about a schema.\n"+
			"A switch with a panicking default keeps compiling when a variant is added,\n"+
			"which is when it stops being right. Use schema.VisitElem with an\n"+
			"ElemVisitor, or return a diagnostic, so the compiler or the user is told.")
}

// TestGeneratedCodeIsMarked checks that every committed .pb.go says so, since
// the point of committing generated code is that a reader can tell.
func TestGeneratedCodeIsMarked(t *testing.T) {
	root, err := filepath.Abs("../..")
	require.NoError(t, err)

	err = filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if d.Name() == ".git" || d.Name() == "node_modules" {
				return fs.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".pb.go") {
			return nil
		}

		src, readErr := os.ReadFile(path)
		if readErr != nil {
			return readErr
		}
		rel, _ := filepath.Rel(root, path)
		// The convention every Go tool recognises, from the generated-code spec.
		require.Contains(t, string(src), "Code generated by",
			"%s does not say it is generated", rel)
		return nil
	})
	require.NoError(t, err)
}
