// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.0-calque
// source: calque/orm/orm.proto

// Package calque.orm is calque's copy of the annotation vocabulary published as
// buf.build/orm/orm by github.com/protobuf-orm/protobuf-orm.
//
// The copy exists so that calque depends on the *contract* rather than on the
// library. Extensions resolve by number, not by name, so a proto that imports
// the upstream "orm.proto" and writes `(orm.field)` decodes through the types
// generated from these files unchanged -- the field numbers are what has to
// match, and testdata/proto/_upstream holds the real upstream files so a test
// can prove it rather than assert it.
//
// Depending on the library instead is what protoc-gen-orm-ts did, and its
// go.mod pins a protobuf-orm older than a method its own code calls, so its
// HEAD does not compile and its committed output was generated against an IR
// newer than its module graph declares. A copy cannot drift that way: it is
// either the same as upstream or a test says it is not.
//
// Only the annotation vocabulary is copied. orm/order.proto and
// orm/patch_op.proto describe the generated request surface rather than the
// annotations, and calque derives that surface itself, so vendoring them would
// imply calque honours something it does not read.

package ormopt

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_calque_orm_orm_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*MessageOptions)(nil),
		Field:         45001,
		Name:          "calque.orm.message",
		Tag:           "bytes,45001,opt,name=message",
		Filename:      "calque/orm/orm.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldOptions)(nil),
		Field:         45101,
		Name:          "calque.orm.field",
		Tag:           "bytes,45101,opt,name=field",
		Filename:      "calque/orm/orm.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*EdgeOptions)(nil),
		Field:         45102,
		Name:          "calque.orm.edge",
		Tag:           "bytes,45102,opt,name=edge",
		Filename:      "calque/orm/orm.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional calque.orm.MessageOptions message = 45001;
	E_Message = &file_calque_orm_orm_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional calque.orm.FieldOptions field = 45101;
	E_Field = &file_calque_orm_orm_proto_extTypes[1]
	// optional calque.orm.EdgeOptions edge = 45102;
	E_Edge = &file_calque_orm_orm_proto_extTypes[2]
)

var File_calque_orm_orm_proto protoreflect.FileDescriptor

const file_calque_orm_orm_proto_rawDesc = "" +
	"\n" +
	"\x14calque/orm/orm.proto\x12\n" +
	"calque.orm\x1a\x18calque/orm/options.proto\x1a google/protobuf/descriptor.proto:W\n" +
	"\amessage\x12\x1f.google.protobuf.MessageOptions\x18\xc9\xdf\x02 \x01(\v2\x1a.calque.orm.MessageOptionsR\amessage:O\n" +
	"\x05field\x12\x1d.google.protobuf.FieldOptions\x18\xad\xe0\x02 \x01(\v2\x18.calque.orm.FieldOptionsR\x05field:L\n" +
	"\x04edge\x12\x1d.google.protobuf.FieldOptions\x18\xae\xe0\x02 \x01(\v2\x17.calque.orm.EdgeOptionsR\x04edgeB%Z#github.com/heojeongbo/calque/ormoptb\beditionsp\xe8\a"

var file_calque_orm_orm_proto_goTypes = []any{
	(*descriptorpb.MessageOptions)(nil), // 0: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 1: google.protobuf.FieldOptions
	(*MessageOptions)(nil),              // 2: calque.orm.MessageOptions
	(*FieldOptions)(nil),                // 3: calque.orm.FieldOptions
	(*EdgeOptions)(nil),                 // 4: calque.orm.EdgeOptions
}
var file_calque_orm_orm_proto_depIdxs = []int32{
	0, // 0: calque.orm.message:extendee -> google.protobuf.MessageOptions
	1, // 1: calque.orm.field:extendee -> google.protobuf.FieldOptions
	1, // 2: calque.orm.edge:extendee -> google.protobuf.FieldOptions
	2, // 3: calque.orm.message:type_name -> calque.orm.MessageOptions
	3, // 4: calque.orm.field:type_name -> calque.orm.FieldOptions
	4, // 5: calque.orm.edge:type_name -> calque.orm.EdgeOptions
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	3, // [3:6] is the sub-list for extension type_name
	0, // [0:3] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_calque_orm_orm_proto_init() }
func file_calque_orm_orm_proto_init() {
	if File_calque_orm_orm_proto != nil {
		return
	}
	file_calque_orm_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_calque_orm_orm_proto_rawDesc), len(file_calque_orm_orm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_calque_orm_orm_proto_goTypes,
		DependencyIndexes: file_calque_orm_orm_proto_depIdxs,
		ExtensionInfos:    file_calque_orm_orm_proto_extTypes,
	}.Build()
	File_calque_orm_orm_proto = out.File
	file_calque_orm_orm_proto_goTypes = nil
	file_calque_orm_orm_proto_depIdxs = nil
}
