package config_test

import (
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/heojeongbo/calque/config"
)

// The tests below are about the reading, not about what any target happens to
// be configured with, so they use a section of their own. It holds every shape
// a section is made of, and it does not change when a target does.

type probe struct {
	Runtime string   `yaml:"runtime"`
	Depth   int      `yaml:"depth"`
	On      bool     `yaml:"on"`
	Accept  []string `yaml:"accept"`

	Nested *nested `yaml:"nested"`
	Inline inlined `yaml:",inline"`

	Renamed  string `yaml:"other_name"`
	Untagged string
	Hidden   string `yaml:"-"`
	private  string //nolint:unused // it is here to prove it is skipped
}

type nested struct {
	Count int `yaml:"count"`
}

type inlined struct {
	Flat string `yaml:"flat"`
}

// claim parses a document, tells it about an environment, and lets `probe`
// claim its section -- which is the whole order a build goes through.
func claim(t *testing.T, doc string, environ []string, opts ...string) (*config.Config, *probe) {
	t.Helper()

	c, err := config.Parse([]byte(doc), "calque.yaml")
	require.NoError(t, err)
	c.ReadEnv(environ)
	for _, o := range opts {
		k, v, _ := cut(o)
		require.NoError(t, c.Override(k, v))
	}

	p := &probe{}
	_, err = c.Section("probe", p)
	require.NoError(t, err)
	return c, p
}

func cut(s string) (string, string, bool) {
	for i := range s {
		if s[i] == '=' {
			return s[:i], s[i+1:], true
		}
	}
	return s, "", false
}

const doc = "version: 1\ntargets:\n  - {target: ts, backend: dexie}\n"

func TestEnv(t *testing.T) {
	t.Run("a value is read into the field it is named after", func(t *testing.T) {
		_, p := claim(t, doc, []string{"CALQUE_PROBE_RUNTIME=@scope/pkg"})
		require.Equal(t, "@scope/pkg", p.Runtime)
	})

	t.Run("a string keeps its punctuation", func(t *testing.T) {
		// A header is a comment, not a mapping. Reading it as YAML would give
		// the colon a meaning.
		const header = "// Code generated by calque. DO NOT EDIT."
		_, p := claim(t, doc, []string{"CALQUE_PROBE_RUNTIME=" + header})
		require.Equal(t, header, p.Runtime)
	})

	t.Run("anything else is read the way the file reads it", func(t *testing.T) {
		_, p := claim(t, doc, []string{
			"CALQUE_PROBE_DEPTH=3",
			"CALQUE_PROBE_ON=true",
			"CALQUE_PROBE_ACCEPT=[binary_key, partial_index]",
		})
		require.Equal(t, 3, p.Depth)
		require.True(t, p.On)
		require.Equal(t, []string{"binary_key", "partial_index"}, p.Accept)
	})

	t.Run("a value is made where there was none", func(t *testing.T) {
		_, p := claim(t, doc, []string{"CALQUE_PROBE_NESTED_COUNT=2"})
		require.NotNil(t, p.Nested)
		require.Equal(t, 2, p.Nested.Count)
	})

	t.Run("nothing is made where nothing was said", func(t *testing.T) {
		_, p := claim(t, doc, []string{"CALQUE_PROBE_RUNTIME=x"})
		require.Nil(t, p.Nested, "looking at the environment must not fill in what nobody set")
	})

	t.Run("an inlined struct adds nothing to the path", func(t *testing.T) {
		_, p := claim(t, doc, []string{"CALQUE_PROBE_FLAT=here"})
		require.Equal(t, "here", p.Inline.Flat)
	})

	t.Run("the yaml tag is the name, and so is its absence", func(t *testing.T) {
		_, p := claim(t, doc, []string{
			"CALQUE_PROBE_OTHER_NAME=renamed",
			"CALQUE_PROBE_UNTAGGED=fallback",
		})
		require.Equal(t, "renamed", p.Renamed)
		require.Equal(t, "fallback", p.Untagged)
	})

	t.Run("what is not read from the file is not read from the environment", func(t *testing.T) {
		c, p := claim(t, doc, []string{"CALQUE_PROBE_HIDDEN=no"})
		require.Empty(t, p.Hidden)
		require.NotContains(t, c.EnvNames("probe"), "CALQUE_PROBE_HIDDEN")
		require.Contains(t, c.UnreadEnv(), "CALQUE_PROBE_HIDDEN")
	})

	t.Run("a value that does not fit is refused by name", func(t *testing.T) {
		c, err := config.Parse([]byte(doc), "calque.yaml")
		require.NoError(t, err)
		c.ReadEnv([]string{"CALQUE_PROBE_DEPTH=deep"})

		_, err = c.Section("probe", &probe{})
		require.ErrorContains(t, err, "CALQUE_PROBE_DEPTH")
	})

	t.Run("a name nothing answers to is reported", func(t *testing.T) {
		c, _ := claim(t, doc, []string{"CALQUE_PROBE_RUNTIMEE=x"})
		require.Equal(t, []string{"CALQUE_PROBE_RUNTIMEE"}, c.UnreadEnv())
		require.Contains(t, c.EnvNames("probe"), "CALQUE_PROBE_RUNTIME",
			"the near miss is only useful beside what it nearly was")
	})

	t.Run("a reserved name is not calque's to report", func(t *testing.T) {
		// The reference tests take their roots this way; a developer who has
		// them exported is not making a typo.
		c, _ := claim(t, doc, []string{"CALQUE_REFERENCE_PROTO=/tmp/app"})
		require.Empty(t, c.UnreadEnv())
	})

	t.Run("the environment beats the file and loses to the command line", func(t *testing.T) {
		const withSection = doc + "probe:\n  runtime: from-file\n  depth: 1\n"

		_, p := claim(t, withSection, []string{"CALQUE_PROBE_RUNTIME=from-env"})
		require.Equal(t, "from-env", p.Runtime)
		require.Equal(t, 1, p.Depth, "the file still holds what the environment said nothing about")

		_, p = claim(t, withSection, []string{"CALQUE_PROBE_RUNTIME=from-env"}, "probe.runtime=from-opt")
		require.Equal(t, "from-opt", p.Runtime)
	})

	t.Run("a section the file never wrote is still claimed", func(t *testing.T) {
		c, p := claim(t, doc, []string{"CALQUE_PROBE_RUNTIME=x"})
		require.Equal(t, "x", p.Runtime)
		require.NoError(t, c.CheckUnclaimed([]string{"probe", "ts", "dexie"}),
			"a section reached only from the environment has been claimed like any other")
	})

	t.Run("what was applied is reported with the section that read it", func(t *testing.T) {
		c, _ := claim(t, doc, []string{"CALQUE_PROBE_RUNTIME=x", "CALQUE_PROBE_DEPTH=2"})
		require.Equal(t, []config.EnvSetting{
			{Name: "CALQUE_PROBE_DEPTH", Section: "probe"},
			{Name: "CALQUE_PROBE_RUNTIME", Section: "probe"},
		}, c.EnvApplied())
	})

	t.Run("nothing is read when nothing is said", func(t *testing.T) {
		c, p := claim(t, doc, nil)
		require.Equal(t, &probe{}, p)
		require.Empty(t, c.EnvApplied())
		require.Empty(t, c.UnreadEnv())
	})
}

// TestAConfigNeverToldAboutTheEnvironmentDoesNotReadOne is what keeps the
// golden tests hermetic, and it is structural rather than a promise.
//
// Those tests build a Config with config.Parse and never call ReadEnv, so no
// ambient variable can reach the bytes they compare. This says the same thing
// where someone changing Section will see it.
func TestAConfigNeverToldAboutTheEnvironmentDoesNotReadOne(t *testing.T) {
	t.Setenv("CALQUE_PROBE_RUNTIME", "would-be-a-disaster")

	c, err := config.Parse([]byte(doc), "calque.yaml")
	require.NoError(t, err)

	p := &probe{}
	_, err = c.Section("probe", p)
	require.NoError(t, err)

	require.Empty(t, p.Runtime, "config.Parse must not reach os.Environ")
	require.Empty(t, c.EnvApplied())
}
